export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  ROLE_CHANGED: "ROLE_CHANGED",
  SESSION_REVOKED: "SESSION_REVOKED",
  TOKEN_REUSE_ATTACK: "TOKEN_REUSE_ATTACK",
};